### PR TITLE
Feature/103 update populate

### PR DESCRIPTION
**Pull request by FelixoGudiel**
This feature aims to change the populate.json file so that it reflects better the current status of the application and its database.

-All enums to spanish (requested by frontend)
-Added missing role EDUCATION_CENTER
-Added populate for suggestion and punctual donation
-Created two new students with status PENDING and REJECTED
-Fixed the routing of avatars (users and students)

### CODE REVIEW

**Review by pabpercab1 — APPROVED** [review]
All the changes you have provided here are working and well implemented. Good job!

**Review by JuanluRM — CHANGES_REQUESTED** [review]
There are some validations tied to the enums on the student-evaluation serializer which stopped working after translating them to spanish. Needs to be fixed and look for other potential changes on the serializers because of that. The other changes seem good.

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
After today's session (19/03) a change is necessary. You have to rename some things to include realist data and remove the faked names, or surnames, among others.

**Comment by FelixoGudiel** [comment]
Thank you both! I have corrected the enum validators, so that the validators expected the translated enums. Also I have added more standard names for all the instances. Please, tell me if you find another problem.

**Review by JuanluRM — APPROVED** [review]
Looks good, well done with the changes.

**Review by pabpercab1 — APPROVED** [review]
You have implemented all the changes proposed, and it works great with the latest develop branch. Well done!

**Comment by MRomalde** [comment]
It works as espected beautiful job !!

**Review by MRomalde — APPROVED** [review]

**Pull request merged**
