### PR TITLE
hotfix/94-meeting-validator

### PR DESCRIPTION
**Pull request by FelixoGudiel**
The validator of the centreexit_auth was copypasted in the meeting serializer. I was responsible for this and i do not remember doing so, either way im sorry for this error. Now it has been removed, allowing the meeting API to work correctly.

To check that it has been corrected, enter the meeting API section and verify that you can send or recieve info.

### CODE REVIEW

**Review by manortbla — APPROVED** [review]
Very fast work, well done. Don't worry about the failure, it can happen to all of us. The important thing is that you have been able to solve it correctly.

Remember to merge develop to your branch.

**Comment by FelixoGudiel** [comment]
You are right, it should be okay now

**Review by JuanluRM — APPROVED** [review]
I also don't remember finding this while reviewing but good thing you noticed this error and thanks for fixing it.

**Review by auroranavas — APPROVED** [review]
I don't know how this slipped past us 😅. However, you did well in fixing it fast!

**Pull request merged**
