### PR TITLE
feature/134 change in models

### PR DESCRIPTION
**Pull request by manortbla**
It has been corrected:

- Changes have been made to the limitation of model fields by frontend request and with the help of the frontend teamleader.
- Enabled the schedule crud so that only admin can create, update and delete and everyone can get.
- Added is_agreed field to default false in the user model, to see if the user accepts the terms and conditions.
- For the verification by email it has been decided that it is activated through the link that is received in the mail without the need to make a post later, now with accessing the link the account will be activated.

### CODE REVIEW

**Review by pedlopruz — APPROVED** [review]
Very good job everything works just as you have conveyed it in the commentary.

**Review by JuanluRM — APPROVED** [review]
Thank you for applying these changes. Everything works as intended.

**Comment by manortbla** [comment]
@pabpercab1 Wouldn't that job be more appropriate from the front? Before there was a problem that was to make the post but now that problem does not exist and that view could be done from the front without problems.

**Comment by pabpercab1** [comment]
@manortbla The thing here is that you are sending in the email the URL from the backend. So if you want to resolve that view in the frontend, the link that you are sending in the email should be tweaked to redirect to a frontend view.

**Comment by manortbla** [comment]
Okey, I'll see what I can do

**Review by pabpercab1 — APPROVED** [review]
Perfect! 👌

**Review by pedlopruz — APPROVED** [review]
Good job

**Review by JuanluRM — APPROVED** [review]

**Pull request merged**
