### PR TITLE
Feature/82-files-organisation

### PR DESCRIPTION
**Pull request by pabpercab1**
The purpose of this feature is to create a structure for the PDFs and other files uploaded to the database. To test it you only have to upload a document to the backend, and you will see how is automatically renamed to avoid collisions. 

In some fields, it's now also required to upload only PDF files, instead of an open file extension.

### CODE REVIEW

**Review by auroranavas — CHANGES_REQUESTED** [review]
I am seeing that in `models.py` you use `validators=[validate_file_extension]` when the FileField should be a PDF. However, I think `quota_extension_document`, `registry_sheet`, `sexual_offenses_document` and `minor_authorization` are PDF files, but you did not set them as such.
Also, I am getting this error when running `python manage.py makemigrations nexong`:

```
Traceback (most recent call last):
  File "C:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 259, in handle
    self.write_migration_files(changes)
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 364, in write_migration_files
    migration_string = writer.as_string()
                       ^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\writer.py", line 141, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\writer.py", line 99, in serialize
    _write(arg_name, arg_value)
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\writer.py", line 51, in _write
    arg_string, arg_imports = MigrationWriter.serialize(item)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\writer.py", line 287, in serialize
    return serializer_factory(value).serialize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\serializer.py", line 42, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\serializer.py", line 231, in serialize
    return self.serialize_deconstructed(path, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\serializer.py", line 96, in serialize_deconstructed
    arg_string, arg_imports = serializer_factory(arg).serialize()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\navas\OneDrive - UNIVERSIDAD DE SEVILLA\CUARTO\ISPP\NexONG_Backend\.venv\Lib\site-packages\django\db\migrations\serializer.py", line 176, in serialize
    raise ValueError("Cannot serialize function: lambda")
ValueError: Cannot serialize function: lambda
```

**Comment by pabpercab1** [comment]
Thanks for the feedback, I will merge this branch with develop, and I will include also that documents that you mention as PDFs

**Review by auroranavas — COMMENTED** [review]
Thank you for taking into account my feedback. Still, I get the same error I got before. Any ideas?

**Review by auroranavas — APPROVED** [review]
Thank you for mitigating the error. The validations work perfectly fine. You did a good job!

**Review by FelixoGudiel — APPROVED** [review]
Works as expected. Really original and interesting idea renaming the files to a random value. Given it is very improbable that a collision occurs, I would say it is the best method to address file names. The file type checkers are also a nice detail. Good job!

**Review by JuanluRM — APPROVED** [review]
Good aproach on the issue, everything works fine. Well done.

**Review by auroranavas — APPROVED** [review]

**Review by JuanluRM — APPROVED** [review]

**Review by Ahydul — APPROVED** [review]
Works as expected, good job!

**Pull request merged**
