### PR TITLE
hotfix/169 fix download privileges

### PR DESCRIPTION
**Pull request by JuanluRM**
Since the download urls are not views, I added a middleware that checks the path looking if it's an export url and then checks if the user is loged as admin otherwise it rejects the access.

I couldn't use the Response from django rest like in the views so I used a normal HTTP response for it, let me know if you want any change on it.

And last remember in order to try some export urls you need to have true pdf files in the database.

### CODE REVIEW

**Review by auroranavas — CHANGES_REQUESTED** [review]
There seems to be a problem here I think. Logged in as an ADMIN I am getting this error: `Acceso denegado`. And I am using the URL http://127.0.0.1:8000/api/export/pdf/partners.

**Comment by JuanluRM** [comment]
Sorry for the inconvenience, I didn't test well enough the functionality. Turns out that the request.user is set in the views so in the middleware the request.user returns anonymous user always. This was fixed by calling the user through the JWT instead, everything works fine now.

The third point mention on the description, the export method will give you an error if you have false pdf files from the populate. You just have to check it redirects correctly.

**Review by auroranavas — APPROVED** [review]
Now it works. Thank you for fixing it. Good work!

**Review by pabpercab1 — APPROVED** [review]
With the feedback that Aurora has provided you, I think that everything now works as expected, and is more secure than before. Good job!

**Pull request merged**
