### PR TITLE
Feature/21-student centreexit

### PR DESCRIPTION
**Pull request by pabpercab1**
This PR adds all the CRUDs methods to the Student and CenterExit Models. It also includes some fixes for other issues.

### CODE REVIEW

**Review by manortbla — COMMENTED** [review]
As advice, in the studentSerializer, in the meta class, I would set it up as follows: 
- fields: "__all__" 

So that if there is any change in the model in the future, it will not be affected.

**Comment by pabpercab1** [comment]
> As advice, in the studentSerializer, in the meta class, I would set it up as follows:
> 
>     * fields: "**all**"
> 
> 
> So that if there is any change in the model in the future, it will not be affected.

Thank you for the great recommendation! I have it taken into account in the last commit in this PR, and it would be great to implement it in all the models. I am very much looking forward to your review.

**Review by auroranavas — CHANGES_REQUESTED** [review]
I tried to POST a Student with a Family but no EducationCenter and got the error: 
```
{
    "education_center": [
        "This field may not be null."
    ]
}
```
Please fix this.

**Comment by pabpercab1** [comment]
> I tried to POST a Student with a Family but no EducationCenter and got the error:
> 
> ```
> {
>     "education_center": [
>         "This field may not be null."
>     ]
> }
> ```
> 
> Please fix this.

Now, it should be solved in the last commit. Thanks for noticing!

**Review by auroranavas — DISMISSED** [review]
Thank you for your quick changes. All the CRUD operations work well. Good job!

**Review by manortbla — DISMISSED** [review]

**Review by FelixoGudiel — APPROVED** [review]
Works correctly. Good job!

**Review by auroranavas — DISMISSED** [review]

**Review by FelixoGudiel — DISMISSED** [review]

**Review by auroranavas — DISMISSED** [review]

**Review by FelixoGudiel — DISMISSED** [review]

**Review by manortbla — APPROVED** [review]

**Review by auroranavas — APPROVED** [review]

**Review by manortbla — APPROVED** [review]

**Review by FelixoGudiel — APPROVED** [review]

**Pull request merged**
