### PR TITLE
Feature/80 export students data

### PR DESCRIPTION
**Pull request by pedlopruz**
I have reverted the deploy merge, check that everything is correct in case I have left anything out that shouldn't be there.
And again I apologise for the inconvenience caused, I will try to be more attentive next time so it doesn't happen again.

### CODE REVIEW

**Review by pabpercab1 — COMMENTED** [review]
Please resolve the conflicts you have, to avoid reviewing the PR multiple times.

**Review by pabpercab1 — COMMENTED** [review]
Your feature works well, with all the changes of the other implemented, so good work. But I am realising that when you export the data of the student, you are exporting as the family column "Family Object (1)", "Family Object (2)"...

**Comment by pedlopruz** [comment]
I am sorry for the error, as the model has changed I didn't realise that the __str__ that already put the names of the families and the educational centre automatically had disappeared, so that it doesn't happen again I have put that inside each function it assigns the names directly.

**Review by pabpercab1 — APPROVED** [review]
You have correctly implemented all the changes proposed as feedback. Now the feature works flawlessly. Good work here!

**Comment by pedlopruz** [comment]
I have been looking at the Codacy errors and it shows me errors that are not in Codacy and therefore I cannot fix them.

**Comment by pabpercab1** [comment]
> I have been looking at the Codacy errors and it shows me errors that are not in Codacy and therefore I cannot fix them.

Please, have a look first here: https://app.codacy.com/gh/ISPP-G5/NexONG_Backend/pullRequest?prid=13929609&bid=40930250#newClonesView

The Codacy suggest that in Student/View.py there are clones in the table style (Line 2290 of your code)

If still does not work, we will change the Codacy policy for this PR.

**Review by pabpercab1 — APPROVED** [review]
Ok! So let's skip Codacy for now. 

Consider adding another one to this PR

**Review by auroranavas — COMMENTED** [review]
How can I test this? What are the endpoints?

**Comment by pedlopruz** [comment]
http://127.0.0.1:8000/api/export/pdf/students
http://127.0.0.1:8000/api/export/csv/students
http://127.0.0.1:8000/api/export/excel/students
http://127.0.0.1:8000/api/export/pdf/students?name=Felipe&nationality=España](http://127.0.0.1:8000/api/export/pdf/students?name=Felipe&nationality=España

Here are some examples

**Review by auroranavas — APPROVED** [review]
This is really nice work. The files come out well formatted and the filters work. Congrats!

**Review by manortbla — APPROVED** [review]
Very good job!

**Pull request merged**
