### PR TITLE
feature/138 tests for admin

### PR DESCRIPTION
**Pull request by pedlopruz**
I have created the tests for admins by checking access to each functionality and validations.
You can check it by doing python **manage.py test**

### CODE REVIEW

**Review by manortbla — APPROVED** [review]
Really good job, you have checked both positive and negative actions on the actions that an admin can take.

**Review by JuanluRM — CHANGES_REQUESTED** [review]
Good job with the tests, but I have to advise you on something: Partner and Educator have now an aditional "description" field added to the model, I suggest you add them to the test otherwise it may give error after updating the database.

**Comment by pedlopruz** [comment]
Thanks for the comment, I don't think that this will generate a problem because in my model those fields are already inserted and it doesn't give error because they are created in raw but I add them without problem.

**Review by JuanluRM — APPROVED** [review]
Thank you for taking it into account, description can be null yes but it's better this way in case it changes in the future. Good job.

**Review by manortbla — APPROVED** [review]

**Pull request merged**
