### PR TITLE
Feature/73 admin authorisation

### PR DESCRIPTION
**Pull request by JuanluRM**
After disscusing this issue with the backend team leader, We agree it's better to manage the authentication in the views instead of the middlewares.

The changes add certain privileges to the administrator role following the criteria written in the requirements:
-Admins can Post, Put, Delete any Events.
-Admins can Post, Put, Delete any Lessons.
-Only Authenticated users can GET Events or Lessons.

This feature has been tested with the latest authentication changes in develop from 19/03.

### CODE REVIEW

**Review by FelixoGudiel — CHANGES_REQUESTED** [review]
The authentication function is well impemented, but it seems that the use of it is not appropiate. Admin is a type of user that has complete control over every type of data, and it seems to me that this PR does not reflect that. Also, I believe that this issue should also include the standard user permissions. I believe that this issue should focus on three variants for each type of data:

-Anyone CRUD
-Anyone read, Admin CRUD
-Admin CRUD only

From this point, the rest of the team can expand depending on the role auth they are assigned (I, for example, am in charge of the families. I would expect to find that Students can only be CRUD by admin, to later add the permission that if the user (family) is associated to that student, they can CRUD)

This way you can also use the function isAdminOnly, that you have updated yet not used.

**Comment by JuanluRM** [comment]
I agree on you on the first regard, in fact, when I looked at the requirements I was suprised the administrator role was this limited. But I was doing what was written on the requirements, I will ask the team leader to double check this is. 

Second, I did not touch anything else that wasn't specificaly for the administrator in order to ease the development of others, but since I see it's not the case, I asked the team leader to give me full control of the permissions issues since it's not as big as we expected and I can put and manage all permissions instead of leaving holes or methods that will be changed later anyway.

The isAdminOnly was done for the first case you mentioned but I didn't found any and I better remove it.

**Review by auroranavas — CHANGES_REQUESTED** [review]
Really good work. I just have these few requests:
**User permissions**
- An admin should be able to POST Educator, as they are the only type of role, apart from admin, that does not register in our platform. So, POST Educator and POST User if the role is Educator.
- As for other roles, Student and User if the role is not Educator, admins should not be able to POST them.

**Donation permissions**
- An admin should not be able to POST donations.

**Quarter Marks permissions**
- An admin should not be able to POST them.

**Comment by JuanluRM** [comment]
Everything was changed according to feedback.

**Review by auroranavas — DISMISSED** [review]
Thank you for taking the feedback into account. It is true that right now, admin can create any type of user and not only of the Educator type, but it seems that those permissions can't be set as usual.

Good job!

**Review by auroranavas — APPROVED** [review]

**Review by pabpercab1 — APPROVED** [review]
I see you have done everything proposed in this issue correctly. Well done!

**Review by FelixoGudiel — APPROVED** [review]

**Pull request merged**
