### PR TITLE
Feature/90-suggestions-quartermarks

### PR DESCRIPTION
**Pull request by auroranavas**
In this PR I added a few features:
- **Quarter marks CRUD**. The date of the marks should not be greater than today.
- **Suggestion model and CRUD**. The text fields shouldn't be empty and the date shouldn't be greater than today.
- **Optional avatar attribute for students** requested by the frontend.

You can test all of these features by performing all the CRUD operations.

### CODE REVIEW

**Review by pabpercab1 — COMMENTED** [review]
I have dropped the database, and I did the migrations, but still, when I try to access suggestion:

`ProgrammingError at /api/suggestion/
relation "nexong_suggestion" does not exist
LINE 1: ...gestion"."email", "nexong_suggestion"."date" FROM "nexong_su...`

**Review by FelixoGudiel — CHANGES_REQUESTED** [review]
Everything works, but I cannot make the populate work. Please, think about updating it.

**Review by FelixoGudiel — APPROVED** [review]
With the new populate, everything works as expected. Great job!

**Comment by MRomalde** [comment]
Everything works as espected! Good work

**Review by MRomalde — APPROVED** [review]

**Review by pabpercab1 — APPROVED** [review]
Now everything works perfectly. Good work!

**Pull request merged**
