### PR TITLE
hotfix/69-remove-the-admin-authentication-for-frontend

### PR DESCRIPTION
**Pull request by JuanluRM**
Removed the necessity to authenticate as admin to do Post, Put and Delete actions in order to ease development for front end.

### CODE REVIEW

**Review by pedlopruz — COMMENTED** [review]
Just a brief change to suggest, it is a good practice to try to remove the commented code you have made in the views.py file because if necessary we can go back to it by looking at the previous commits, otherwise everything is fine.
Good work

**Review by manortbla — APPROVED** [review]
After the changes, everything is perfect. Good job.

**Review by pedlopruz — APPROVED** [review]
Good work

**Review by pabpercab1 — APPROVED** [review]
Good work fixing the problem!

**Pull request merged**
