### PR TITLE
feature/117-payment-method

### PR DESCRIPTION
**Pull request by MRomalde**
Added payment method for sandbox. To prove it you have to call the URL: http://localhost:8000/api/process-payment
With an amount parameter to the body like this:
{
    "amount": 2000
}

### CODE REVIEW

**Comment by MRomalde** [comment]
Forgot to say you, that the call to the URL has to be in POST method

**Review by pabpercab1 — COMMENTED** [review]
Hey! Good job implementing the payment, but I have a question for you, where are you storing the data of the payment? Because the issue talked about a new table called "Punctual donations by card"

**Comment by MRomalde** [comment]
Now in the call to the URL, you have to put this parameters in the body:
{
    "amount": 2000,
    "name": "pepe",
    "surname": "picapiedra",
    "email": "pepe@papi.es",
    "date": "2024-01-16"
}

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
This branch was merged with the deployed version which can cause some errors, please remove the deploy features of this branch. Merge this branch again with develop.

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
Please, include the version that you have used of stripe in the `requirements.txt`

**Comment by pabpercab1** [comment]
I will fix that by myself, but it's odd that you have in the `urls.py`file the endpoints of the student export feature when it is not in develop.
```
File "/home/pablo/Documents/ISPP/NexONG Backend/src/urls.py", line 6, in ‹module> from nexong.api.urls import urlpatterns as api_urls
File "/home/pablo/Documents/ISPP/NexONG_Backend/nexong/api/urls.py", line 41, in <module> path ("export/csv/students", StudentsExportToCsv, name="export_csv_all_students"),
NameError: name 'StudentsExportlocsv is not defined
```

**Comment by pabpercab1** [comment]
I have a few questions, once I tested your feature it seems it works, but:

- Why when I put an amount of 20 a 500 Internal error server popout saying that is $0.10 and it is too low. Why the number is not double?
- Why is there a conversion? Why the amount is in $ and its coverting it to €. The whole process should be carried out using euros and without any conversion.
- Where is the actual payment? Why is the transaction saying that is complete only with the POST? Where is the link to the stripe checkout to introduce card, etc?
- Why a user can POST to the actual `PunctualDonationByCard` skipping the payment wall?

I don't know if I am skipping one of your steps, but please explain how you are managing those things, or solve them if there are not implemented yet.

**Comment by MRomalde** [comment]
Yeah as i talked to you, it was a missunderstanding how about the checkout was going to work. Thanks for the information.

**Review by pedlopruz — APPROVED** [review]
Good work

**Review by pedlopruz — APPROVED** [review]

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
Well done with the checkout, but after successfully completing it, I am redirected to `http://localhost:8000/api/payment/success` that shows:

`{"error": "Error al realizar la solicitud POST", "status": "failed"} `

Also, if "http://localhost:8000/api/punctual-donation-by-card/" it is not the entry point do not allow to POST, only to get.

Finally, consider that the date should not be allowed in any endpoint, it should be Date.now() by default.

**Comment by MRomalde** [comment]
It seems that when the code was merged the changes reverted to te last version, so the code did not work. I have made a commit with the code of the last version.

**Review by pedlopruz — APPROVED** [review]

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
Now it seems that works properly.

Still you have to only allow to the admin to do a GET operation and only stripe/Django internally should do the POST method, so this last one will be not available to anyone.

**Review by pabpercab1 — APPROVED** [review]
Now the feature works properly. Well done! 

Although, I would recommend contacting the frontend responsible for this task, to find out who has to implement the success or error screen. (Backend with HTML or the frontend)

**Review by pedlopruz — APPROVED** [review]

**Pull request merged**
