### PR TITLE
Feature/110 email validation

### PR DESCRIPTION
**Pull request by manortbla**
Email authentication has been implemented using djoser. So that you can see how it works, I leave explained the sequence to follow:
First we create a user, when it is created an email will be sent to the user's email. The user will be created with the checkbox unchecked:
image
The email is:
image
If you access the url below you can see the following view:
image
if you make the post, after updating the user's admin view you will see that the user is authenticated.

### CODE REVIEW

**Review by Ahydul — COMMENTED** [review]
src/urls.py -> path("activate/<uid>/<token>", CustomActivateView.as_view()),
    
This shoudnt be in the general urls paths. It should be inside the /api endpoint (the other ruls.py file in nexong/api)

nexong/api/urls.py -> path("api/", include("djoser.urls"))

This makes no sense, the djoser.urls are already included in the path /api in src/urls.py. That endpoint would be /api/api.

**Comment by manortbla** [comment]
You are right, already corrected. Thanks for your comment

**Review by Ahydul — APPROVED** [review]
Thanks for correcting those small details. The feature works as intended, good job!

**Review by pedlopruz — APPROVED** [review]
Good work, solved the previous problem and everything is fine.

**Review by pabpercab1 — APPROVED** [review]
I have tested your feature, and it works perfectly. Well done. It was very nicely explained also.

Just as a suggestion, consider stopping using the Django admin panel and using the API interface instead.

**Comment by manortbla** [comment]
Thanks for the suggestion, I will take it into account.

**Pull request merged**
