### PR TITLE
feature/140 tests for student  family

### PR DESCRIPTION
**Pull request by pedlopruz**
I have created the tests for students and families by checking access to each functionality and validations. 
You can check it by doing **python manage.py test**

### CODE REVIEW

**Review by manortbla — DISMISSED** [review]
Great job. I think most of the possibilities are covered.

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
The tests seems that covers most of the business logic, so good work with that. But for me one of the tests fails, so please, check what is the problem.

```
FAIL: test_create_family (nexong.api.Authentication.tests.FamilyApiViewSetTestCase.test_create_family)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pablo/Documents/ISPP/NexONG_Backend/nexong/api/Authentication/tests.py", line 21, in test_create_family
    self.assertEqual(response.status_code, 201)
AssertionError: 403 != 201

----------------------------------------------------------------------
Ran 18 tests in 0.532s

FAILED (failures=1)
```

**Review by manortbla — APPROVED** [review]
All possible actions have been successfully tested on the family role. The scope of the tests has been extended to cover everything after the previous feedback. In total I found 34 tests. Very good work!

**Review by pabpercab1 — APPROVED** [review]
Now everything works as expected. You did a really good job with all the tests! I am impressed with the final amount of it. Nice one!

**Pull request merged**
