### PR TITLE
feature/88-backend-documentation

### PR DESCRIPTION
**Pull request by manortbla**
The backend api documentation has been created using swagger. Now all the api functionalities can be accessed via http://127.0.0.1:8000/docs/.
In addition, we have added to the requirements.txt the necessary installation for this to be done (drf-yasg==1.21.7).
To the reviewers, remember to run pip install -r requirements.txt again. 

If you have any questions or suggestions, don't hesitate to comment.

### CODE REVIEW

**Review by pabpercab1 — COMMENTED** [review]
It works great. So good job! But still, I will consider two things:

For me, I had to manually install "setuptools" (pip install setuptools) to work properly, so consider adding them in the requirements.txt

Also, most of the operations seem to work correctly, but some POST and PUT methods do not work because require a file. Do you have something planned to solve this?

**Comment by pedlopruz** [comment]
Thanks for the feedback, first of all we will add the new dependency without problem and secondly the post and put that fail are not related to the installation of swagger. Swagger with Django rest api generates it automatically from the api and the models created, so these errors may be due to what in the model who implemented the add documents missing specify the media path of these files and that's why it does not find them. I have been looking for information and nothing I find that it is a swagger problem.

**Review by FelixoGudiel — COMMENTED** [review]
I have personally worked in the file management section and it is now fixed. Since i am finishing on it, I would wait for me to upload the changes and try if the swagger detects the route.

**Comment by manortbla** [comment]
The setuptools installation has been added to the requirements.txt. We are wating for Felix´s review when he uploads the routes.

**Comment by FelixoGudiel** [comment]
The routes are now uploaded in develop. If there is anything you need help with, give a heads up.

**Review by FelixoGudiel — APPROVED** [review]
Great job! I understand that swagger does not support direct file uploading in jsons, so as this section is supposed to be a guide for frontend and not to be directly used to send the jsons, I excuse this quirk.  Either way, I am really happy it does allow for PATCH petitions! This wll surely ease the work of the frontend so that they udnerstand how it works. The basic operations for everything work as expected. Overall, very happy with the result!

**Review by auroranavas — APPROVED** [review]
I agree with @FelixoGudiel, I understand that file uploading is not allowed in Swagger via JSON. Nevertheless, Swagger allows for a better general visualization of the API, so it will be useful for our frontend developers.

**Comment by pedlopruz** [comment]
Thanks Again Thanks again for your interactions, as you have been commenting the model attributes for file storage are not supported by Swagger because Swagger itself does not access the functionality of Swagger as the API itself. 
I attach information obtained from Chat gpt after searching for information from other sources to generate a promt that summarises the content well.
Captura de pantalla 2024-03-17 115742

**Review by auroranavas — APPROVED** [review]

**Review by pabpercab1 — APPROVED** [review]

**Pull request merged**
