### PR TITLE
feature/93-puntual-donations--home-documents-models-and-crud

### PR DESCRIPTION
**Pull request by MRomalde**
Added cruds needed for punctual donations and home documents

### CODE REVIEW

**Review by pedlopruz — COMMENTED** [review]
Nice work, just one negative addendum to your implementation, which I think affects in general many other implementations. When you create any donation or home documentation, it does it correctly, but the documents it stores indicate that it doesn't exist, but it's not your fault.

**Review by pedlopruz — APPROVED** [review]

**Review by pedlopruz — DISMISSED** [review]

**Review by auroranavas — APPROVED** [review]
You did a really good job. Thank you for taking into account the feedback I gave you. Let's keep up the good work! 👌

**Review by pedlopruz — APPROVED** [review]
Good Job

**Review by auroranavas — APPROVED** [review]

**Review by pabpercab1 — APPROVED** [review]
Nice job solving this issue. The fix looks good, and solved the problem that we had! 👍

**Pull request merged**
