### PR TITLE
feature/81-export-dontations-donation-data

### PR DESCRIPTION
**Pull request by MRomalde**
Developed new code, making an exportation of all donations in the application. I have removed the admin authentication for using the CRUD.
You can prove the code in the URL: localhost:8000/api/donation/export.
If the code needs any change, please comment me.

### CODE REVIEW

**Review by Ahydul — CHANGES_REQUESTED** [review]
Everything works as expected. The only problem I see is that the urlpattern used is not appropiate. You can review the changes in PR feature/83 related to routers and urls to add the url in a better way.

**Comment by MRomalde** [comment]
Added the new url pattern, reviewed in feature/83
Also added the exportation in pdf.

**Review by pabpercab1 — DISMISSED** [review]
`ModuleNotFoundError: No module named 'reportlab'`

Be sure to update requirements.txt if you have added any new modules.

**Comment by MRomalde** [comment]
Updated requirements.txt.

**Review by Ahydul — DISMISSED** [review]
Perfect!

**Review by pedlopruz — DISMISSED** [review]
Good Work

**Review by Ahydul — DISMISSED** [review]

**Review by pabpercab1 — COMMENTED** [review]
Good work exporting the data! It works great. However, can you explain how to export data in a selected range o with a filter? Is it using query params? 

Can you also try to format the pdf document? For example, include the logo a title, the export date, the range selected for the export, a table with the data...

This is for the Sprint 2, so you still have time :)

**Comment by MRomalde** [comment]
Yeah it use query parameters to get the data of the database, and you can format the pdf, at least the plain text i really dont know  about the logo, or tables.

**Comment by pabpercab1** [comment]
> Yeah it use query parameters to get the data of the database, and you can format the pdf, at least the plain text i really dont know about the logo, or tables.

Can you explain in the pull request how to use the parameters? Also, as I said before, you still have time for this task, so, can you implement a proper PFD format for this? Also, take into consideration that some tasks will require yours to do so. If you still can't figure out how to implement this, the library that you are using has published a comprehensive guide to do so:

https://docs.reportlab.com/reportlab/userguide/ch1_intro/

**Comment by MRomalde** [comment]
Hi guys i have developped new code for PDF exportation to use query parameters, it has a table for the database data and the logo of the ONG, also the actual date and if you use dates for the query parameters it appear in the document too.
To use it you have to call to this URL: **http://localhost:8000/api/export/pdf/donations?startdate=2023-01-01&enddate=2024-12-31&partner=1**, this is the 3 query parameters that I use.
startdate and enddate is mandatory that if startdate is in the query parameters we need the enddate too, it needs to be both at the same time. You can call the url with no parameters, with only partner, with startdate and enddate or all parameters.

**Review by manortbla — DISMISSED** [review]
Excelent work! They can be downloaded both in excel and pdf correctly, applying filters or in general.

**Review by pabpercab1 — COMMENTED** [review]
I saw the PDF before, and congratulations! It was an impressive job on that. However, at the moment, it is not working for me, Am I doing something wrong?

```Environment:


Request Method: GET
Request URL: http://localhost:8000/api/export/pdf/donations

Django Version: 5.0.2
Python Version: 3.11.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'nexong',
 'corsheaders']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/pablo/Documents/ISPP/NexONG_Backend/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pablo/Documents/ISPP/NexONG_Backend/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pablo/Documents/ISPP/NexONG_Backend/nexong/api/Donation/views.py", line 125, in DonationsExportToPdf
    (
    ^

Exception Type: ValueError at /api/export/pdf/donations
Exception Value: too many values to unpack (expected 8)
```

**Comment by MRomalde** [comment]
The format of the codacy change how it takes the arguments so it went wrong, all should be ok now

**Review by pedlopruz — APPROVED** [review]

**Review by auroranavas — COMMENTED** [review]
Right now I am getting this error:

image

Am I doing something wrong?

**Comment by MRomalde** [comment]
The problem was that develop had an urls.py not updated and when i merged, it kept the urls.py from develop and it was not configurated. All should be okay now

**Review by pedlopruz — APPROVED** [review]
Good job, all works correctly

**Review by auroranavas — APPROVED** [review]
My most honest congratulations to you. The PDF is formatted really nicely and the filters are really useful. You did a good job!

**Review by FelixoGudiel — APPROVED** [review]
Good job! The 3 urls work as expected.

**Pull request merged**
