### PR TITLE
Feature/79 export volunteers/volunteer data

### PR DESCRIPTION
**Pull request by JuanluRM**
This feature adds the option to download pdf, csv and excel files of the volunteers data stored in the database. ~Additionally you can download all 3 files compressed in a zip.~

The urls to download the files are:
-api/export/pdf/volunteers
-api/export/csv/volunteers
-api/export/excel/volunteers
~-api/export/all/volunteers~

Update: The zip function has been changed to download all documents relative to volunteers, you can access through this url: 
-api/export/files/volunteers
Also, all options have filters now for the first_name, last_name and volunteer status fields. You can set the parameters in the url with:
-[url]?name=value&surname=value&status=value
Name and surname are not case sensitive but status being an Enum needs to be exact. And the current populate doesn't work to test this function since it creates volunteers but doesn't upload documents, you have to upload some pdf documents to the database and then test it.

### CODE REVIEW

**Review by pedlopruz — CHANGES_REQUESTED** [review]
Very good work, the functionality works well although there are some things that can be improved:
-First of all, when exporting the csv of volunteers the tildes are not read well by my functionality so you can fix it by adding "smart_str" in the attributes, see export students data to see how.
- The second thing is that you haven't done any filtering, try to do at least three filters, name, surname and other fields that you think are convenient. And have them generate the files depending on the fields they provide.

**Comment by JuanluRM** [comment]
Thanks for your feedback, unfortunately, the accent mark is not an issue of the export but of the configuration of the reader program, all data is exported correctly. On the other hand, filters for first name, last name and status of the volunteers have been added for all types of exports, you can try it out like this: api/export/[type]/volunteers?name=value&surname=value&status=value. Tell me if more filters are needed.

**Comment by pabpercab1** [comment]
Please consider creating a new volunteer folder to store there all the code related to the csv, excel & pdf export

**Comment by JuanluRM** [comment]
After checking requirements again, I have changed the export zip function to export the volunteers attached documents which was the objective of the function. The URL was changed to api/export/files/volunteers and the filters added before work as well. Note that in order to test this function you need to have pdf files uploaded to the volunteers database, the current populate won't work. 
All new code was moved to a new file as proposed by @pabpercab1.

**Review by manortbla — APPROVED** [review]
Thank you for applying the feedback. Well done.

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
Its weid because even having the files in the correct folders, this error pop out when I try `/api/export/files/volunteers`:
imagen

```
Exception Type: FileNotFoundError at /api/export/files/volunteers
Exception Value: [Errno 2] No such file or directory: '/home/pablo/Documents/ISPP/NexONG_Backend/files
/volunteer enrollment\\volunteer_enrollment.txt
```

Probably is something related to the use of \\ or combining / and \ in the same route.

**Review by pedlopruz — APPROVED** [review]
Sorry for taking so long to do the review, everything is correct, good job.

**Pull request merged**
