### PR TITLE
feature/55-donation-crud

### PR DESCRIPTION
**Pull request by Ahydul**

### CODE REVIEW

**Comment by MRomalde** [comment]
All seems to be ok, nice job

**Review by MRomalde — DISMISSED** [review]

**Review by FelixoGudiel — APPROVED** [review]
Works as expected, good job!

**Review by pabpercab1 — COMMENTED** [review]
Looks good! All the methods are working. But I suggest changing to decimal the quantity model:
```
    quantity = models.DecimalField(
        default=Decimal("0.01"),
        validators=[MinValueValidator(Decimal("0.01"))],
        max_digits=10,
        decimal_places=2,
    )
```

**Comment by Ahydul** [comment]
> Looks good! All the methods are working. But I suggest changing to decimal the quantity model:
> 
> ```
>     quantity = models.DecimalField(
>         default=Decimal("0.01"),
>         validators=[MinValueValidator(Decimal("0.01"))],
>         max_digits=10,
>         decimal_places=2,
>     )
> ```

This is not part of my task, it's a mistake in the DB but I've commited it either way.

**Review by pabpercab1 — APPROVED** [review]
Good job! And thanks for changing also the bug in the model!

**Review by auroranavas — APPROVED** [review]
All the CRUD operations work. Good work! 👍

**Review by JuanluRM — APPROVED** [review]
Working as intended, well done.

**Pull request merged**
