### PR TITLE
Feature/80 export students data

### PR DESCRIPTION
**Pull request by pedlopruz**
I have implemented the export of students in both pdf and csv format.
You can access the urls :
http://127.0.0.1:8000/export/csv/students and http://127.0.0.1:8000/export/pdf/students to try it out.
Any suggestions for changes let me know in the comments.

### CODE REVIEW

**Review by FelixoGudiel — DISMISSED** [review]
I thought that it didn't work, but I have found that the URLs that you have given are incorrect. I will add the correct ones in this comment, so that other reviewers can try them out directly. 

http://127.0.0.1:8000/api/export/pdf/students
http://127.0.0.1:8000/api/export/csv/students

Apart from that, works as expected. Good job!

**Review by manortbla — APPROVED** [review]
Thanks @FelixoGudiel for the correct urls. Both the excel and the pdf download correctly. Well done.
Remember to update from develop.

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
Thank you for submitting your feature so early, but can you please add the Excel export, query parameters, and donations task?

Sorry about that, It was implemented in last week's issue, but I forgot to add it in the ones of this week.

**Comment by pedlopruz** [comment]
Thanks for the comments, first of all, sorry for the urls I do not know how it could have happened and secondly I do the new without any problem the only thing is that in donations the parameters were around two dates in this case that filtering would be the most appropriate

**Comment by pabpercab1** [comment]
> Thanks for the comments, first of all, sorry for the urls I do not know how it could have happened and secondly I do the new without any problem the only thing is that in donations the parameters were around two dates in this case that filtering would be the most appropriate

Of course! In this case, it would be great to have a filter based on the name, surname, family, nationality, if it's a morning student or even the lesson on which the student is enrolled if you think it's possible.

**Comment by pedlopruz** [comment]
I have finished implementing the export in Pdf and excel of students with the filters. You can filter to test by adding the fields name, surname, nationality, family and is a moning student.
These are some of the urls that you can test although you can make about 30 different combinations specifying one or the other:
http://127.0.0.1:8000/api/export/pdf/students?name=Felipe&nationality=España
http://127.0.0.1:8000/api/export/csv/students?surname=Moreno&family=Familia Moreno
If you want me to change some of the attributes for others, let me know, although I tell you that it is already excessive so many filters because you have to combine all with all.

**Review by pabpercab1 — COMMENTED** [review]
Well done! I think that the feature is much better now!

However, can you consider also adding a filter considering the current education year and the status? Because I believe that these are important filters when in the future the app contains a lot of data. 

Also, I tried this query http://127.0.0.1:8000/api/export/pdf/students?isamorningstudent=True and seems it is not working for me. 

Finally, Can you try to add the query to the document name as the feature of last week?

Thank you so much!

**Comment by pedlopruz** [comment]
Thank you for your comment, I will immediately add the two you have told me to filter in the query. The url of is a moning student does not work because I have put it only morning because I consider the name too long for a query. I also implement the name in the title without any problem.

**Comment by pedlopruz** [comment]
I have just implemented the 2 new filters with their correct filenames. These are an example to test, but you can try all the options:
http://127.0.0.1:8000/api/export/pdf/students?morning=False&status=PENDIENTE
http://127.0.0.1:8000/api/export/pdf/students?education_year=CUARTO PRIMARIA

**Comment by FelixoGudiel** [comment]
Seems like the second link does not work. I would think about changing all the enums to a pattern like CUARTO_PRIMARIA instead of CUARTO PRIMARIA so that it can be understood as a single URL.

**Comment by pedlopruz** [comment]
The problem is with GitHub because it interprets it as outside the URL, but if you copy it and paste it in the browser there is no problem.

**Review by FelixoGudiel — DISMISSED** [review]
You are right. Everythong seems in order then!

**Review by manortbla — DISMISSED** [review]

**Review by pabpercab1 — APPROVED** [review]
The feature works like a charm. Good work!

**Review by pabpercab1 — APPROVED** [review]

**Review by manortbla — APPROVED** [review]

**Review by FelixoGudiel — APPROVED** [review]

**Pull request merged**
