### PR TITLE
hotfix/148-fix-user-roles

### PR DESCRIPTION
**Pull request by JuanluRM**
Changed permissions on roles so Admins can change roles and the owners of the roles can put and post their own roles.

### CODE REVIEW

**Review by pabpercab1 — COMMENTED** [review]
Now, it works like it was expected. Many thanks for working on this issue. Only remember, if it is feasible to fix the permission of the HomeDocument model, that at the moment everyone can edit, and also you must be logged in to see.

**Review by pabpercab1 — APPROVED** [review]
👌

**Review by auroranavas — APPROVED** [review]
Thank you for fixing the issue quickly!

**Review by MRomalde — APPROVED** [review]
Nice work!! All seems to work properly!

**Pull request merged**
