### PR TITLE
feature/109-punctual-donations-in-the-donations-export

### PR DESCRIPTION
**Pull request by MRomalde**
Added exportations to pdf and excel, same as donations export. There is only one change, in the query parameters, we cant filter by partner.
This is excel URL: http://localhost:8000/api/export/excel/punctualdonations?startdate=2023-01-01&enddate=2024-12-31
This is pdf URL: http://localhost:8000/api/export/pdf/punctualdonations?startdate=2023-01-01&enddate=2024-12-31

### CODE REVIEW

**Review by FelixoGudiel — CHANGES_REQUESTED** [review]
Works fine. It is nice detail that you can filter by date, but if I try to give only a start date or end date, the app fails. Could you change it so that it also works with one parameter given? Also, I believe that filtering by partner is not possible because punctualDonations is not related to partners, but given first and last names.

**Comment by MRomalde** [comment]
Since the Front-End will control the start date and end date it has to be both if the user selects a date, if you want to get all donations from a period of time, you only have to put start dante from the day you want to start and end date, the date you are doing the request.

**Review by manortbla — APPROVED** [review]
All works as expected. Good job.

**Review by pabpercab1 — APPROVED** [review]
It works beautifully as the one you created last week. You did a great job here!

**Pull request merged**
